import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import AuthProvider from "@/components/auth-provider";
import { UserNav } from "@/components/user-nav";
import { NextIntlClientProvider } from 'next-intl'; // Import NextIntlClientProvider
import { getMessages } from 'next-intl/server'; // Import getMessages
import LocaleSwitcher from "@/components/locale-switcher"; // Import LocaleSwitcher

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages(); // Fetch messages

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AuthProvider>
              <div className="fixed top-4 right-4 flex items-center space-x-4">
                <UserNav />
                <ModeToggle />
                <LocaleSwitcher /> {/* Added LocaleSwitcher */}
              </div>
              {children}
            </AuthProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

