/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { checkout_acss_debit_payment_method_options } from './checkout_acss_debit_payment_method_options';
import type { checkout_affirm_payment_method_options } from './checkout_affirm_payment_method_options';
import type { checkout_afterpay_clearpay_payment_method_options } from './checkout_afterpay_clearpay_payment_method_options';
import type { checkout_alipay_payment_method_options } from './checkout_alipay_payment_method_options';
import type { checkout_amazon_pay_payment_method_options } from './checkout_amazon_pay_payment_method_options';
import type { checkout_au_becs_debit_payment_method_options } from './checkout_au_becs_debit_payment_method_options';
import type { checkout_bacs_debit_payment_method_options } from './checkout_bacs_debit_payment_method_options';
import type { checkout_bancontact_payment_method_options } from './checkout_bancontact_payment_method_options';
import type { checkout_boleto_payment_method_options } from './checkout_boleto_payment_method_options';
import type { checkout_card_payment_method_options } from './checkout_card_payment_method_options';
import type { checkout_cashapp_payment_method_options } from './checkout_cashapp_payment_method_options';
import type { checkout_customer_balance_payment_method_options } from './checkout_customer_balance_payment_method_options';
import type { checkout_eps_payment_method_options } from './checkout_eps_payment_method_options';
import type { checkout_fpx_payment_method_options } from './checkout_fpx_payment_method_options';
import type { checkout_giropay_payment_method_options } from './checkout_giropay_payment_method_options';
import type { checkout_grab_pay_payment_method_options } from './checkout_grab_pay_payment_method_options';
import type { checkout_ideal_payment_method_options } from './checkout_ideal_payment_method_options';
import type { checkout_kakao_pay_payment_method_options } from './checkout_kakao_pay_payment_method_options';
import type { checkout_klarna_payment_method_options } from './checkout_klarna_payment_method_options';
import type { checkout_konbini_payment_method_options } from './checkout_konbini_payment_method_options';
import type { checkout_kr_card_payment_method_options } from './checkout_kr_card_payment_method_options';
import type { checkout_link_payment_method_options } from './checkout_link_payment_method_options';
import type { checkout_mobilepay_payment_method_options } from './checkout_mobilepay_payment_method_options';
import type { checkout_multibanco_payment_method_options } from './checkout_multibanco_payment_method_options';
import type { checkout_naver_pay_payment_method_options } from './checkout_naver_pay_payment_method_options';
import type { checkout_oxxo_payment_method_options } from './checkout_oxxo_payment_method_options';
import type { checkout_p24_payment_method_options } from './checkout_p24_payment_method_options';
import type { checkout_payco_payment_method_options } from './checkout_payco_payment_method_options';
import type { checkout_paynow_payment_method_options } from './checkout_paynow_payment_method_options';
import type { checkout_paypal_payment_method_options } from './checkout_paypal_payment_method_options';
import type { checkout_pix_payment_method_options } from './checkout_pix_payment_method_options';
import type { checkout_revolut_pay_payment_method_options } from './checkout_revolut_pay_payment_method_options';
import type { checkout_samsung_pay_payment_method_options } from './checkout_samsung_pay_payment_method_options';
import type { checkout_sepa_debit_payment_method_options } from './checkout_sepa_debit_payment_method_options';
import type { checkout_sofort_payment_method_options } from './checkout_sofort_payment_method_options';
import type { checkout_swish_payment_method_options } from './checkout_swish_payment_method_options';
import type { checkout_us_bank_account_payment_method_options } from './checkout_us_bank_account_payment_method_options';
export type checkout_session_payment_method_options = {
    acss_debit?: checkout_acss_debit_payment_method_options;
    affirm?: checkout_affirm_payment_method_options;
    afterpay_clearpay?: checkout_afterpay_clearpay_payment_method_options;
    alipay?: checkout_alipay_payment_method_options;
    amazon_pay?: checkout_amazon_pay_payment_method_options;
    au_becs_debit?: checkout_au_becs_debit_payment_method_options;
    bacs_debit?: checkout_bacs_debit_payment_method_options;
    bancontact?: checkout_bancontact_payment_method_options;
    boleto?: checkout_boleto_payment_method_options;
    card?: checkout_card_payment_method_options;
    cashapp?: checkout_cashapp_payment_method_options;
    customer_balance?: checkout_customer_balance_payment_method_options;
    eps?: checkout_eps_payment_method_options;
    fpx?: checkout_fpx_payment_method_options;
    giropay?: checkout_giropay_payment_method_options;
    grabpay?: checkout_grab_pay_payment_method_options;
    ideal?: checkout_ideal_payment_method_options;
    kakao_pay?: checkout_kakao_pay_payment_method_options;
    klarna?: checkout_klarna_payment_method_options;
    konbini?: checkout_konbini_payment_method_options;
    kr_card?: checkout_kr_card_payment_method_options;
    link?: checkout_link_payment_method_options;
    mobilepay?: checkout_mobilepay_payment_method_options;
    multibanco?: checkout_multibanco_payment_method_options;
    naver_pay?: checkout_naver_pay_payment_method_options;
    oxxo?: checkout_oxxo_payment_method_options;
    p24?: checkout_p24_payment_method_options;
    payco?: checkout_payco_payment_method_options;
    paynow?: checkout_paynow_payment_method_options;
    paypal?: checkout_paypal_payment_method_options;
    pix?: checkout_pix_payment_method_options;
    revolut_pay?: checkout_revolut_pay_payment_method_options;
    samsung_pay?: checkout_samsung_pay_payment_method_options;
    sepa_debit?: checkout_sepa_debit_payment_method_options;
    sofort?: checkout_sofort_payment_method_options;
    swish?: checkout_swish_payment_method_options;
    us_bank_account?: checkout_us_bank_account_payment_method_options;
};

