/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { connect_account_reference } from './connect_account_reference';
import type { deleted_tax_id } from './deleted_tax_id';
import type { tax_id } from './tax_id';
export type invoice_setting_subscription_schedule_phase_setting = {
    /**
     * The account tax IDs associated with this phase of the subscription schedule. Will be set on invoices generated by this phase of the subscription schedule.
     */
    account_tax_ids?: Array<(string | tax_id | deleted_tax_id)> | null;
    /**
     * Number of days within which a customer must pay invoices generated by this subscription schedule. This value will be `null` for subscription schedules where `billing=charge_automatically`.
     */
    days_until_due?: number | null;
    /**
     * The connected account that issues the invoice. The invoice is presented with the branding and support information of the specified account.
     */
    issuer?: connect_account_reference | null;
};

