/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type mandate_paypal = {
    /**
     * The PayPal Billing Agreement ID (BAID). This is an ID generated by PayPal which represents the mandate between the merchant and the customer.
     */
    billing_agreement_id?: string | null;
    /**
     * PayPal account PayerID. This identifier uniquely identifies the PayPal customer.
     */
    payer_id?: string | null;
};

