/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { paypal_seller_protection } from './paypal_seller_protection';
export type payment_method_details_paypal = {
    /**
     * Two-letter ISO code representing the buyer's country. Values are provided by PayPal directly (if supported) at the time of authorization or settlement. They cannot be set or mutated.
     */
    country?: string | null;
    /**
     * Owner's email. Values are provided by PayPal directly
     * (if supported) at the time of authorization or settlement. They cannot be set or mutated.
     */
    payer_email?: string | null;
    /**
     * PayPal account PayerID. This identifier uniquely identifies the PayPal customer.
     */
    payer_id?: string | null;
    /**
     * Owner's full name. Values provided by PayPal directly
     * (if supported) at the time of authorization or settlement. They cannot be set or mutated.
     */
    payer_name?: string | null;
    /**
     * The level of protection offered as defined by PayPal Seller Protection for Merchants, for this transaction.
     */
    seller_protection?: paypal_seller_protection | null;
    /**
     * A unique ID generated by PayPal for this transaction.
     */
    transaction_id?: string | null;
};

