/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { mandate } from './mandate';
import type { payment_method } from './payment_method';
export type payment_method_details_sofort = {
    /**
     * Bank code of bank associated with the bank account.
     */
    bank_code?: string | null;
    /**
     * Name of the bank associated with the bank account.
     */
    bank_name?: string | null;
    /**
     * Bank Identifier Code of the bank associated with the bank account.
     */
    bic?: string | null;
    /**
     * Two-letter ISO code representing the country the bank account is located in.
     */
    country?: string | null;
    /**
     * The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
     */
    generated_sepa_debit?: (string | payment_method) | null;
    /**
     * The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
     */
    generated_sepa_debit_mandate?: (string | mandate) | null;
    /**
     * Last four characters of the IBAN.
     */
    iban_last4?: string | null;
    /**
     * Preferred language of the SOFORT authorization page that the customer is redirected to.
     * Can be one of `de`, `en`, `es`, `fr`, `it`, `nl`, or `pl`
     */
    preferred_language?: payment_method_details_sofort.preferred_language | null;
    /**
     * Owner's verified full name. Values are verified or provided by SOFORT directly
     * (if supported) at the time of authorization or settlement. They cannot be set or mutated.
     */
    verified_name?: string | null;
};
export namespace payment_method_details_sofort {
    /**
     * Preferred language of the SOFORT authorization page that the customer is redirected to.
     * Can be one of `de`, `en`, `es`, `fr`, `it`, `nl`, or `pl`
     */
    export enum preferred_language {
        DE = 'de',
        EN = 'en',
        ES = 'es',
        FR = 'fr',
        IT = 'it',
        NL = 'nl',
        PL = 'pl',
    }
}

