/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { account } from './account';
import type { api_errors } from './api_errors';
import type { application } from './application';
import type { charge } from './charge';
import type { customer } from './customer';
import type { deleted_customer } from './deleted_customer';
import type { payment_flows_amount_details } from './payment_flows_amount_details';
import type { payment_flows_amount_details_client } from './payment_flows_amount_details_client';
import type { payment_flows_automatic_payment_methods_payment_intent } from './payment_flows_automatic_payment_methods_payment_intent';
import type { payment_flows_payment_intent_presentment_details } from './payment_flows_payment_intent_presentment_details';
import type { payment_intent_next_action } from './payment_intent_next_action';
import type { payment_intent_payment_method_options } from './payment_intent_payment_method_options';
import type { payment_intent_processing } from './payment_intent_processing';
import type { payment_method } from './payment_method';
import type { payment_method_config_biz_payment_method_configuration_details } from './payment_method_config_biz_payment_method_configuration_details';
import type { review } from './review';
import type { shipping } from './shipping';
import type { transfer_data } from './transfer_data';
/**
 * A PaymentIntent guides you through the process of collecting a payment from your customer.
 * We recommend that you create exactly one PaymentIntent for each order or
 * customer session in your system. You can reference the PaymentIntent later to
 * see the history of payment attempts for a particular session.
 *
 * A PaymentIntent transitions through
 * [multiple statuses](https://stripe.com/docs/payments/intents#intent-statuses)
 * throughout its lifetime as it interfaces with Stripe.js to perform
 * authentication flows and ultimately creates at most one successful charge.
 *
 * Related guide: [Payment Intents API](https://stripe.com/docs/payments/payment-intents)
 */
export type payment_intent = {
    /**
     * Amount intended to be collected by this PaymentIntent. A positive integer representing how much to charge in the [smallest currency unit](https://stripe.com/docs/currencies#zero-decimal) (e.g., 100 cents to charge $1.00 or 100 to charge ¥100, a zero-decimal currency). The minimum amount is $0.50 US or [equivalent in charge currency](https://stripe.com/docs/currencies#minimum-and-maximum-charge-amounts). The amount value supports up to eight digits (e.g., a value of 99999999 for a USD charge of $999,999.99).
     */
    amount?: number;
    /**
     * Amount that can be captured from this PaymentIntent.
     */
    amount_capturable?: number;
    amount_details?: (payment_flows_amount_details | payment_flows_amount_details_client);
    /**
     * Amount that this PaymentIntent collects.
     */
    amount_received?: number;
    /**
     * ID of the Connect application that created the PaymentIntent.
     */
    application?: (string | application) | null;
    /**
     * The amount of the application fee (if any) that will be requested to be applied to the payment and transferred to the application owner's Stripe account. The amount of the application fee collected will be capped at the total amount captured. For more information, see the PaymentIntents [use case for connected accounts](https://stripe.com/docs/payments/connected-accounts).
     */
    application_fee_amount?: number | null;
    /**
     * Settings to configure compatible payment methods from the [Stripe Dashboard](https://dashboard.stripe.com/settings/payment_methods)
     */
    automatic_payment_methods?: payment_flows_automatic_payment_methods_payment_intent | null;
    /**
     * Populated when `status` is `canceled`, this is the time at which the PaymentIntent was canceled. Measured in seconds since the Unix epoch.
     */
    canceled_at?: number | null;
    /**
     * Reason for cancellation of this PaymentIntent, either user-provided (`duplicate`, `fraudulent`, `requested_by_customer`, or `abandoned`) or generated by Stripe internally (`failed_invoice`, `void_invoice`, `automatic`, or `expired`).
     */
    cancellation_reason?: payment_intent.cancellation_reason | null;
    /**
     * Controls when the funds will be captured from the customer's account.
     */
    capture_method?: payment_intent.capture_method;
    /**
     * The client secret of this PaymentIntent. Used for client-side retrieval using a publishable key.
     *
     * The client secret can be used to complete a payment from your frontend. It should not be stored, logged, or exposed to anyone other than the customer. Make sure that you have TLS enabled on any page that includes the client secret.
     *
     * Refer to our docs to [accept a payment](https://stripe.com/docs/payments/accept-a-payment?ui=elements) and learn about how `client_secret` should be handled.
     */
    client_secret?: string | null;
    /**
     * Describes whether we can confirm this PaymentIntent automatically, or if it requires customer action to confirm the payment.
     */
    confirmation_method?: payment_intent.confirmation_method;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created: number;
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
     */
    currency?: string;
    /**
     * ID of the Customer this PaymentIntent belongs to, if one exists.
     *
     * Payment methods attached to other Customers cannot be used with this PaymentIntent.
     *
     * If [setup_future_usage](https://stripe.com/docs/api#payment_intent_object-setup_future_usage) is set and this PaymentIntent's payment method is not `card_present`, then the payment method attaches to the Customer after the PaymentIntent has been confirmed and any required actions from the user are complete. If the payment method is `card_present` and isn't a digital wallet, then a [generated_card](https://docs.stripe.com/api/charges/object#charge_object-payment_method_details-card_present-generated_card) payment method representing the card is created and attached to the Customer instead.
     */
    customer?: (string | customer | deleted_customer) | null;
    /**
     * An arbitrary string attached to the object. Often useful for displaying to users.
     */
    description?: string | null;
    /**
     * The list of payment method types to exclude from use with this payment.
     */
    excluded_payment_method_types?: Array<'acss_debit' | 'affirm' | 'afterpay_clearpay' | 'alipay' | 'alma' | 'amazon_pay' | 'au_becs_debit' | 'bacs_debit' | 'bancontact' | 'billie' | 'blik' | 'boleto' | 'card' | 'cashapp' | 'crypto' | 'customer_balance' | 'eps' | 'fpx' | 'giropay' | 'grabpay' | 'ideal' | 'kakao_pay' | 'klarna' | 'konbini' | 'kr_card' | 'mobilepay' | 'multibanco' | 'naver_pay' | 'nz_bank_account' | 'oxxo' | 'p24' | 'pay_by_bank' | 'payco' | 'paynow' | 'paypal' | 'pix' | 'promptpay' | 'revolut_pay' | 'samsung_pay' | 'satispay' | 'sepa_debit' | 'sofort' | 'swish' | 'twint' | 'us_bank_account' | 'wechat_pay' | 'zip'> | null;
    /**
     * Unique identifier for the object.
     */
    id: string;
    /**
     * The payment error encountered in the previous PaymentIntent confirmation. It will be cleared if the PaymentIntent is later updated for any reason.
     */
    last_payment_error?: api_errors | null;
    /**
     * ID of the latest [Charge object](https://stripe.com/docs/api/charges) created by this PaymentIntent. This property is `null` until PaymentIntent confirmation is attempted.
     */
    latest_charge?: (string | charge) | null;
    /**
     * Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
     */
    livemode: boolean;
    /**
     * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Learn more about [storing information in metadata](https://stripe.com/docs/payments/payment-intents/creating-payment-intents#storing-information-in-metadata).
     */
    metadata?: Record<string, string>;
    next_action?: payment_intent_next_action | null;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object: payment_intent.object;
    /**
     * The account (if any) for which the funds of the PaymentIntent are intended. See the PaymentIntents [use case for connected accounts](https://stripe.com/docs/payments/connected-accounts) for details.
     */
    on_behalf_of?: (string | account) | null;
    /**
     * ID of the payment method used in this PaymentIntent.
     */
    payment_method?: (string | payment_method) | null;
    /**
     * Information about the [payment method configuration](https://stripe.com/docs/api/payment_method_configurations) used for this PaymentIntent.
     */
    payment_method_configuration_details?: payment_method_config_biz_payment_method_configuration_details | null;
    /**
     * Payment-method-specific configuration for this PaymentIntent.
     */
    payment_method_options?: payment_intent_payment_method_options | null;
    /**
     * The list of payment method types (e.g. card) that this PaymentIntent is allowed to use. A comprehensive list of valid payment method types can be found [here](https://docs.stripe.com/api/payment_methods/object#payment_method_object-type).
     */
    payment_method_types?: Array<string>;
    presentment_details?: payment_flows_payment_intent_presentment_details;
    /**
     * If present, this property tells you about the processing state of the payment.
     */
    processing?: payment_intent_processing | null;
    /**
     * Email address that the receipt for the resulting payment will be sent to. If `receipt_email` is specified for a payment in live mode, a receipt will be sent regardless of your [email settings](https://dashboard.stripe.com/account/emails).
     */
    receipt_email?: string | null;
    /**
     * ID of the review associated with this PaymentIntent, if any.
     */
    review?: (string | review) | null;
    /**
     * Indicates that you intend to make future payments with this PaymentIntent's payment method.
     *
     * If you provide a Customer with the PaymentIntent, you can use this parameter to [attach the payment method](/payments/save-during-payment) to the Customer after the PaymentIntent is confirmed and the customer completes any required actions. If you don't provide a Customer, you can still [attach](/api/payment_methods/attach) the payment method to a Customer after the transaction completes.
     *
     * If the payment method is `card_present` and isn't a digital wallet, Stripe creates and attaches a [generated_card](/api/charges/object#charge_object-payment_method_details-card_present-generated_card) payment method representing the card to the Customer instead.
     *
     * When processing card payments, Stripe uses `setup_future_usage` to help you comply with regional legislation and network rules, such as [SCA](/strong-customer-authentication).
     */
    setup_future_usage?: payment_intent.setup_future_usage | null;
    /**
     * Shipping information for this PaymentIntent.
     */
    shipping?: shipping | null;
    /**
     * Text that appears on the customer's statement as the statement descriptor for a non-card charge. This value overrides the account's default statement descriptor. For information about requirements, including the 22-character limit, see [the Statement Descriptor docs](https://docs.stripe.com/get-started/account/statement-descriptors).
     *
     * Setting this value for a card charge returns an error. For card charges, set the [statement_descriptor_suffix](https://docs.stripe.com/get-started/account/statement-descriptors#dynamic) instead.
     */
    statement_descriptor?: string | null;
    /**
     * Provides information about a card charge. Concatenated to the account's [statement descriptor prefix](https://docs.stripe.com/get-started/account/statement-descriptors#static) to form the complete statement descriptor that appears on the customer's statement.
     */
    statement_descriptor_suffix?: string | null;
    /**
     * Status of this PaymentIntent, one of `requires_payment_method`, `requires_confirmation`, `requires_action`, `processing`, `requires_capture`, `canceled`, or `succeeded`. Read more about each PaymentIntent [status](https://stripe.com/docs/payments/intents#intent-statuses).
     */
    status: payment_intent.status;
    /**
     * The data that automatically creates a Transfer after the payment finalizes. Learn more about the [use case for connected accounts](https://stripe.com/docs/payments/connected-accounts).
     */
    transfer_data?: transfer_data | null;
    /**
     * A string that identifies the resulting payment as part of a group. Learn more about the [use case for connected accounts](https://stripe.com/docs/connect/separate-charges-and-transfers).
     */
    transfer_group?: string | null;
};
export namespace payment_intent {
    /**
     * Reason for cancellation of this PaymentIntent, either user-provided (`duplicate`, `fraudulent`, `requested_by_customer`, or `abandoned`) or generated by Stripe internally (`failed_invoice`, `void_invoice`, `automatic`, or `expired`).
     */
    export enum cancellation_reason {
        ABANDONED = 'abandoned',
        AUTOMATIC = 'automatic',
        DUPLICATE = 'duplicate',
        EXPIRED = 'expired',
        FAILED_INVOICE = 'failed_invoice',
        FRAUDULENT = 'fraudulent',
        REQUESTED_BY_CUSTOMER = 'requested_by_customer',
        VOID_INVOICE = 'void_invoice',
    }
    /**
     * Controls when the funds will be captured from the customer's account.
     */
    export enum capture_method {
        AUTOMATIC = 'automatic',
        AUTOMATIC_ASYNC = 'automatic_async',
        MANUAL = 'manual',
    }
    /**
     * Describes whether we can confirm this PaymentIntent automatically, or if it requires customer action to confirm the payment.
     */
    export enum confirmation_method {
        AUTOMATIC = 'automatic',
        MANUAL = 'manual',
    }
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    export enum object {
        PAYMENT_INTENT = 'payment_intent',
    }
    /**
     * Indicates that you intend to make future payments with this PaymentIntent's payment method.
     *
     * If you provide a Customer with the PaymentIntent, you can use this parameter to [attach the payment method](/payments/save-during-payment) to the Customer after the PaymentIntent is confirmed and the customer completes any required actions. If you don't provide a Customer, you can still [attach](/api/payment_methods/attach) the payment method to a Customer after the transaction completes.
     *
     * If the payment method is `card_present` and isn't a digital wallet, Stripe creates and attaches a [generated_card](/api/charges/object#charge_object-payment_method_details-card_present-generated_card) payment method representing the card to the Customer instead.
     *
     * When processing card payments, Stripe uses `setup_future_usage` to help you comply with regional legislation and network rules, such as [SCA](/strong-customer-authentication).
     */
    export enum setup_future_usage {
        OFF_SESSION = 'off_session',
        ON_SESSION = 'on_session',
    }
    /**
     * Status of this PaymentIntent, one of `requires_payment_method`, `requires_confirmation`, `requires_action`, `processing`, `requires_capture`, `canceled`, or `succeeded`. Read more about each PaymentIntent [status](https://stripe.com/docs/payments/intents#intent-statuses).
     */
    export enum status {
        CANCELED = 'canceled',
        PROCESSING = 'processing',
        REQUIRES_ACTION = 'requires_action',
        REQUIRES_CAPTURE = 'requires_capture',
        REQUIRES_CONFIRMATION = 'requires_confirmation',
        REQUIRES_PAYMENT_METHOD = 'requires_payment_method',
        SUCCEEDED = 'succeeded',
    }
}

