/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type payment_method_details_promptpay = {
    /**
     * Bill reference generated by PromptPay
     */
    reference?: string | null;
};

