/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type payment_method_details_card_present_receipt = {
    /**
     * The type of account being debited or credited
     */
    account_type?: payment_method_details_card_present_receipt.account_type;
    /**
     * The Application Cryptogram, a unique value generated by the card to authenticate the transaction with issuers.
     */
    application_cryptogram?: string | null;
    /**
     * The Application Identifier (AID) on the card used to determine which networks are eligible to process the transaction. Referenced from EMV tag 9F12, data encoded on the card's chip.
     */
    application_preferred_name?: string | null;
    /**
     * Identifier for this transaction.
     */
    authorization_code?: string | null;
    /**
     * EMV tag 8A. A code returned by the card issuer.
     */
    authorization_response_code?: string | null;
    /**
     * Describes the method used by the cardholder to verify ownership of the card. One of the following: `approval`, `failure`, `none`, `offline_pin`, `offline_pin_and_signature`, `online_pin`, or `signature`.
     */
    cardholder_verification_method?: string | null;
    /**
     * Similar to the application_preferred_name, identifying the applications (AIDs) available on the card. Referenced from EMV tag 84.
     */
    dedicated_file_name?: string | null;
    /**
     * A 5-byte string that records the checks and validations that occur between the card and the terminal. These checks determine how the terminal processes the transaction and what risk tolerance is acceptable. Referenced from EMV Tag 95.
     */
    terminal_verification_results?: string | null;
    /**
     * An indication of which steps were completed during the card read process. Referenced from EMV Tag 9B.
     */
    transaction_status_information?: string | null;
};
export namespace payment_method_details_card_present_receipt {
    /**
     * The type of account being debited or credited
     */
    export enum account_type {
        CHECKING = 'checking',
        CREDIT = 'credit',
        PREPAID = 'prepaid',
        UNKNOWN = 'unknown',
    }
}

