/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { payment_flows_private_payment_methods_kakao_pay_payment_method_options } from './payment_flows_private_payment_methods_kakao_pay_payment_method_options';
import type { payment_flows_private_payment_methods_naver_pay_payment_method_options } from './payment_flows_private_payment_methods_naver_pay_payment_method_options';
import type { payment_flows_private_payment_methods_payco_payment_method_options } from './payment_flows_private_payment_methods_payco_payment_method_options';
import type { payment_flows_private_payment_methods_samsung_pay_payment_method_options } from './payment_flows_private_payment_methods_samsung_pay_payment_method_options';
import type { payment_intent_payment_method_options_acss_debit } from './payment_intent_payment_method_options_acss_debit';
import type { payment_intent_payment_method_options_au_becs_debit } from './payment_intent_payment_method_options_au_becs_debit';
import type { payment_intent_payment_method_options_bacs_debit } from './payment_intent_payment_method_options_bacs_debit';
import type { payment_intent_payment_method_options_blik } from './payment_intent_payment_method_options_blik';
import type { payment_intent_payment_method_options_card } from './payment_intent_payment_method_options_card';
import type { payment_intent_payment_method_options_eps } from './payment_intent_payment_method_options_eps';
import type { payment_intent_payment_method_options_link } from './payment_intent_payment_method_options_link';
import type { payment_intent_payment_method_options_mobilepay } from './payment_intent_payment_method_options_mobilepay';
import type { payment_intent_payment_method_options_nz_bank_account } from './payment_intent_payment_method_options_nz_bank_account';
import type { payment_intent_payment_method_options_sepa_debit } from './payment_intent_payment_method_options_sepa_debit';
import type { payment_intent_payment_method_options_swish } from './payment_intent_payment_method_options_swish';
import type { payment_intent_payment_method_options_us_bank_account } from './payment_intent_payment_method_options_us_bank_account';
import type { payment_intent_type_specific_payment_method_options_client } from './payment_intent_type_specific_payment_method_options_client';
import type { payment_method_options_affirm } from './payment_method_options_affirm';
import type { payment_method_options_afterpay_clearpay } from './payment_method_options_afterpay_clearpay';
import type { payment_method_options_alipay } from './payment_method_options_alipay';
import type { payment_method_options_alma } from './payment_method_options_alma';
import type { payment_method_options_amazon_pay } from './payment_method_options_amazon_pay';
import type { payment_method_options_bancontact } from './payment_method_options_bancontact';
import type { payment_method_options_billie } from './payment_method_options_billie';
import type { payment_method_options_boleto } from './payment_method_options_boleto';
import type { payment_method_options_card_present } from './payment_method_options_card_present';
import type { payment_method_options_cashapp } from './payment_method_options_cashapp';
import type { payment_method_options_crypto } from './payment_method_options_crypto';
import type { payment_method_options_customer_balance } from './payment_method_options_customer_balance';
import type { payment_method_options_fpx } from './payment_method_options_fpx';
import type { payment_method_options_giropay } from './payment_method_options_giropay';
import type { payment_method_options_grabpay } from './payment_method_options_grabpay';
import type { payment_method_options_ideal } from './payment_method_options_ideal';
import type { payment_method_options_interac_present } from './payment_method_options_interac_present';
import type { payment_method_options_klarna } from './payment_method_options_klarna';
import type { payment_method_options_konbini } from './payment_method_options_konbini';
import type { payment_method_options_kr_card } from './payment_method_options_kr_card';
import type { payment_method_options_multibanco } from './payment_method_options_multibanco';
import type { payment_method_options_oxxo } from './payment_method_options_oxxo';
import type { payment_method_options_p24 } from './payment_method_options_p24';
import type { payment_method_options_pay_by_bank } from './payment_method_options_pay_by_bank';
import type { payment_method_options_paynow } from './payment_method_options_paynow';
import type { payment_method_options_paypal } from './payment_method_options_paypal';
import type { payment_method_options_pix } from './payment_method_options_pix';
import type { payment_method_options_promptpay } from './payment_method_options_promptpay';
import type { payment_method_options_revolut_pay } from './payment_method_options_revolut_pay';
import type { payment_method_options_satispay } from './payment_method_options_satispay';
import type { payment_method_options_sofort } from './payment_method_options_sofort';
import type { payment_method_options_twint } from './payment_method_options_twint';
import type { payment_method_options_wechat_pay } from './payment_method_options_wechat_pay';
import type { payment_method_options_zip } from './payment_method_options_zip';
export type payment_intent_payment_method_options = {
    acss_debit?: (payment_intent_payment_method_options_acss_debit | payment_intent_type_specific_payment_method_options_client);
    affirm?: (payment_method_options_affirm | payment_intent_type_specific_payment_method_options_client);
    afterpay_clearpay?: (payment_method_options_afterpay_clearpay | payment_intent_type_specific_payment_method_options_client);
    alipay?: (payment_method_options_alipay | payment_intent_type_specific_payment_method_options_client);
    alma?: (payment_method_options_alma | payment_intent_type_specific_payment_method_options_client);
    amazon_pay?: (payment_method_options_amazon_pay | payment_intent_type_specific_payment_method_options_client);
    au_becs_debit?: (payment_intent_payment_method_options_au_becs_debit | payment_intent_type_specific_payment_method_options_client);
    bacs_debit?: (payment_intent_payment_method_options_bacs_debit | payment_intent_type_specific_payment_method_options_client);
    bancontact?: (payment_method_options_bancontact | payment_intent_type_specific_payment_method_options_client);
    billie?: (payment_method_options_billie | payment_intent_type_specific_payment_method_options_client);
    blik?: (payment_intent_payment_method_options_blik | payment_intent_type_specific_payment_method_options_client);
    boleto?: (payment_method_options_boleto | payment_intent_type_specific_payment_method_options_client);
    card?: (payment_intent_payment_method_options_card | payment_intent_type_specific_payment_method_options_client);
    card_present?: (payment_method_options_card_present | payment_intent_type_specific_payment_method_options_client);
    cashapp?: (payment_method_options_cashapp | payment_intent_type_specific_payment_method_options_client);
    crypto?: (payment_method_options_crypto | payment_intent_type_specific_payment_method_options_client);
    customer_balance?: (payment_method_options_customer_balance | payment_intent_type_specific_payment_method_options_client);
    eps?: (payment_intent_payment_method_options_eps | payment_intent_type_specific_payment_method_options_client);
    fpx?: (payment_method_options_fpx | payment_intent_type_specific_payment_method_options_client);
    giropay?: (payment_method_options_giropay | payment_intent_type_specific_payment_method_options_client);
    grabpay?: (payment_method_options_grabpay | payment_intent_type_specific_payment_method_options_client);
    ideal?: (payment_method_options_ideal | payment_intent_type_specific_payment_method_options_client);
    interac_present?: (payment_method_options_interac_present | payment_intent_type_specific_payment_method_options_client);
    kakao_pay?: (payment_flows_private_payment_methods_kakao_pay_payment_method_options | payment_intent_type_specific_payment_method_options_client);
    klarna?: (payment_method_options_klarna | payment_intent_type_specific_payment_method_options_client);
    konbini?: (payment_method_options_konbini | payment_intent_type_specific_payment_method_options_client);
    kr_card?: (payment_method_options_kr_card | payment_intent_type_specific_payment_method_options_client);
    link?: (payment_intent_payment_method_options_link | payment_intent_type_specific_payment_method_options_client);
    mobilepay?: (payment_intent_payment_method_options_mobilepay | payment_intent_type_specific_payment_method_options_client);
    multibanco?: (payment_method_options_multibanco | payment_intent_type_specific_payment_method_options_client);
    naver_pay?: (payment_flows_private_payment_methods_naver_pay_payment_method_options | payment_intent_type_specific_payment_method_options_client);
    nz_bank_account?: (payment_intent_payment_method_options_nz_bank_account | payment_intent_type_specific_payment_method_options_client);
    oxxo?: (payment_method_options_oxxo | payment_intent_type_specific_payment_method_options_client);
    p24?: (payment_method_options_p24 | payment_intent_type_specific_payment_method_options_client);
    pay_by_bank?: (payment_method_options_pay_by_bank | payment_intent_type_specific_payment_method_options_client);
    payco?: (payment_flows_private_payment_methods_payco_payment_method_options | payment_intent_type_specific_payment_method_options_client);
    paynow?: (payment_method_options_paynow | payment_intent_type_specific_payment_method_options_client);
    paypal?: (payment_method_options_paypal | payment_intent_type_specific_payment_method_options_client);
    pix?: (payment_method_options_pix | payment_intent_type_specific_payment_method_options_client);
    promptpay?: (payment_method_options_promptpay | payment_intent_type_specific_payment_method_options_client);
    revolut_pay?: (payment_method_options_revolut_pay | payment_intent_type_specific_payment_method_options_client);
    samsung_pay?: (payment_flows_private_payment_methods_samsung_pay_payment_method_options | payment_intent_type_specific_payment_method_options_client);
    satispay?: (payment_method_options_satispay | payment_intent_type_specific_payment_method_options_client);
    sepa_debit?: (payment_intent_payment_method_options_sepa_debit | payment_intent_type_specific_payment_method_options_client);
    sofort?: (payment_method_options_sofort | payment_intent_type_specific_payment_method_options_client);
    swish?: (payment_intent_payment_method_options_swish | payment_intent_type_specific_payment_method_options_client);
    twint?: (payment_method_options_twint | payment_intent_type_specific_payment_method_options_client);
    us_bank_account?: (payment_intent_payment_method_options_us_bank_account | payment_intent_type_specific_payment_method_options_client);
    wechat_pay?: (payment_method_options_wechat_pay | payment_intent_type_specific_payment_method_options_client);
    zip?: (payment_method_options_zip | payment_intent_type_specific_payment_method_options_client);
};

