/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type payment_method_details_pix = {
    /**
     * Unique transaction id generated by BCB
     */
    bank_transaction_id?: string | null;
};

