/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type payment_pages_checkout_session_tax_id = {
    /**
     * The type of the tax ID, one of `ad_nrt`, `ar_cuit`, `eu_vat`, `bo_tin`, `br_cnpj`, `br_cpf`, `cn_tin`, `co_nit`, `cr_tin`, `do_rcn`, `ec_ruc`, `eu_oss_vat`, `hr_oib`, `pe_ruc`, `ro_tin`, `rs_pib`, `sv_nit`, `uy_ruc`, `ve_rif`, `vn_tin`, `gb_vat`, `nz_gst`, `au_abn`, `au_arn`, `in_gst`, `no_vat`, `no_voec`, `za_vat`, `ch_vat`, `mx_rfc`, `sg_uen`, `ru_inn`, `ru_kpp`, `ca_bn`, `hk_br`, `es_cif`, `tw_vat`, `th_vat`, `jp_cn`, `jp_rn`, `jp_trn`, `li_uid`, `li_vat`, `my_itn`, `us_ein`, `kr_brn`, `ca_qst`, `ca_gst_hst`, `ca_pst_bc`, `ca_pst_mb`, `ca_pst_sk`, `my_sst`, `sg_gst`, `ae_trn`, `cl_tin`, `sa_vat`, `id_npwp`, `my_frp`, `il_vat`, `ge_vat`, `ua_vat`, `is_vat`, `bg_uic`, `hu_tin`, `si_tin`, `ke_pin`, `tr_tin`, `eg_tin`, `ph_tin`, `al_tin`, `bh_vat`, `kz_bin`, `ng_tin`, `om_vat`, `de_stn`, `ch_uid`, `tz_vat`, `uz_vat`, `uz_tin`, `md_vat`, `ma_vat`, `by_tin`, `ao_tin`, `bs_tin`, `bb_tin`, `cd_nif`, `mr_nif`, `me_pib`, `zw_tin`, `ba_tin`, `gn_nif`, `mk_vat`, `sr_fin`, `sn_ninea`, `am_tin`, `np_pan`, `tj_tin`, `ug_tin`, `zm_tin`, `kh_tin`, `aw_tin`, `az_tin`, `bd_bin`, `bj_ifu`, `et_tin`, `kg_tin`, `la_tin`, `cm_niu`, `cv_nif`, `bf_ifu`, or `unknown`
     */
    type: payment_pages_checkout_session_tax_id.type;
    /**
     * The value of the tax ID.
     */
    value?: string | null;
};
export namespace payment_pages_checkout_session_tax_id {
    /**
     * The type of the tax ID, one of `ad_nrt`, `ar_cuit`, `eu_vat`, `bo_tin`, `br_cnpj`, `br_cpf`, `cn_tin`, `co_nit`, `cr_tin`, `do_rcn`, `ec_ruc`, `eu_oss_vat`, `hr_oib`, `pe_ruc`, `ro_tin`, `rs_pib`, `sv_nit`, `uy_ruc`, `ve_rif`, `vn_tin`, `gb_vat`, `nz_gst`, `au_abn`, `au_arn`, `in_gst`, `no_vat`, `no_voec`, `za_vat`, `ch_vat`, `mx_rfc`, `sg_uen`, `ru_inn`, `ru_kpp`, `ca_bn`, `hk_br`, `es_cif`, `tw_vat`, `th_vat`, `jp_cn`, `jp_rn`, `jp_trn`, `li_uid`, `li_vat`, `my_itn`, `us_ein`, `kr_brn`, `ca_qst`, `ca_gst_hst`, `ca_pst_bc`, `ca_pst_mb`, `ca_pst_sk`, `my_sst`, `sg_gst`, `ae_trn`, `cl_tin`, `sa_vat`, `id_npwp`, `my_frp`, `il_vat`, `ge_vat`, `ua_vat`, `is_vat`, `bg_uic`, `hu_tin`, `si_tin`, `ke_pin`, `tr_tin`, `eg_tin`, `ph_tin`, `al_tin`, `bh_vat`, `kz_bin`, `ng_tin`, `om_vat`, `de_stn`, `ch_uid`, `tz_vat`, `uz_vat`, `uz_tin`, `md_vat`, `ma_vat`, `by_tin`, `ao_tin`, `bs_tin`, `bb_tin`, `cd_nif`, `mr_nif`, `me_pib`, `zw_tin`, `ba_tin`, `gn_nif`, `mk_vat`, `sr_fin`, `sn_ninea`, `am_tin`, `np_pan`, `tj_tin`, `ug_tin`, `zm_tin`, `kh_tin`, `aw_tin`, `az_tin`, `bd_bin`, `bj_ifu`, `et_tin`, `kg_tin`, `la_tin`, `cm_niu`, `cv_nif`, `bf_ifu`, or `unknown`
     */
    export enum type {
        AD_NRT = 'ad_nrt',
        AE_TRN = 'ae_trn',
        AL_TIN = 'al_tin',
        AM_TIN = 'am_tin',
        AO_TIN = 'ao_tin',
        AR_CUIT = 'ar_cuit',
        AU_ABN = 'au_abn',
        AU_ARN = 'au_arn',
        AW_TIN = 'aw_tin',
        AZ_TIN = 'az_tin',
        BA_TIN = 'ba_tin',
        BB_TIN = 'bb_tin',
        BD_BIN = 'bd_bin',
        BF_IFU = 'bf_ifu',
        BG_UIC = 'bg_uic',
        BH_VAT = 'bh_vat',
        BJ_IFU = 'bj_ifu',
        BO_TIN = 'bo_tin',
        BR_CNPJ = 'br_cnpj',
        BR_CPF = 'br_cpf',
        BS_TIN = 'bs_tin',
        BY_TIN = 'by_tin',
        CA_BN = 'ca_bn',
        CA_GST_HST = 'ca_gst_hst',
        CA_PST_BC = 'ca_pst_bc',
        CA_PST_MB = 'ca_pst_mb',
        CA_PST_SK = 'ca_pst_sk',
        CA_QST = 'ca_qst',
        CD_NIF = 'cd_nif',
        CH_UID = 'ch_uid',
        CH_VAT = 'ch_vat',
        CL_TIN = 'cl_tin',
        CM_NIU = 'cm_niu',
        CN_TIN = 'cn_tin',
        CO_NIT = 'co_nit',
        CR_TIN = 'cr_tin',
        CV_NIF = 'cv_nif',
        DE_STN = 'de_stn',
        DO_RCN = 'do_rcn',
        EC_RUC = 'ec_ruc',
        EG_TIN = 'eg_tin',
        ES_CIF = 'es_cif',
        ET_TIN = 'et_tin',
        EU_OSS_VAT = 'eu_oss_vat',
        EU_VAT = 'eu_vat',
        GB_VAT = 'gb_vat',
        GE_VAT = 'ge_vat',
        GN_NIF = 'gn_nif',
        HK_BR = 'hk_br',
        HR_OIB = 'hr_oib',
        HU_TIN = 'hu_tin',
        ID_NPWP = 'id_npwp',
        IL_VAT = 'il_vat',
        IN_GST = 'in_gst',
        IS_VAT = 'is_vat',
        JP_CN = 'jp_cn',
        JP_RN = 'jp_rn',
        JP_TRN = 'jp_trn',
        KE_PIN = 'ke_pin',
        KG_TIN = 'kg_tin',
        KH_TIN = 'kh_tin',
        KR_BRN = 'kr_brn',
        KZ_BIN = 'kz_bin',
        LA_TIN = 'la_tin',
        LI_UID = 'li_uid',
        LI_VAT = 'li_vat',
        MA_VAT = 'ma_vat',
        MD_VAT = 'md_vat',
        ME_PIB = 'me_pib',
        MK_VAT = 'mk_vat',
        MR_NIF = 'mr_nif',
        MX_RFC = 'mx_rfc',
        MY_FRP = 'my_frp',
        MY_ITN = 'my_itn',
        MY_SST = 'my_sst',
        NG_TIN = 'ng_tin',
        NO_VAT = 'no_vat',
        NO_VOEC = 'no_voec',
        NP_PAN = 'np_pan',
        NZ_GST = 'nz_gst',
        OM_VAT = 'om_vat',
        PE_RUC = 'pe_ruc',
        PH_TIN = 'ph_tin',
        RO_TIN = 'ro_tin',
        RS_PIB = 'rs_pib',
        RU_INN = 'ru_inn',
        RU_KPP = 'ru_kpp',
        SA_VAT = 'sa_vat',
        SG_GST = 'sg_gst',
        SG_UEN = 'sg_uen',
        SI_TIN = 'si_tin',
        SN_NINEA = 'sn_ninea',
        SR_FIN = 'sr_fin',
        SV_NIT = 'sv_nit',
        TH_VAT = 'th_vat',
        TJ_TIN = 'tj_tin',
        TR_TIN = 'tr_tin',
        TW_VAT = 'tw_vat',
        TZ_VAT = 'tz_vat',
        UA_VAT = 'ua_vat',
        UG_TIN = 'ug_tin',
        UNKNOWN = 'unknown',
        US_EIN = 'us_ein',
        UY_RUC = 'uy_ruc',
        UZ_TIN = 'uz_tin',
        UZ_VAT = 'uz_vat',
        VE_RIF = 've_rif',
        VN_TIN = 'vn_tin',
        ZA_VAT = 'za_vat',
        ZM_TIN = 'zm_tin',
        ZW_TIN = 'zw_tin',
    }
}

