/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type payment_method_details_grabpay = {
    /**
     * Unique transaction id generated by GrabPay
     */
    transaction_id?: string | null;
};

