/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { balance_transaction } from './balance_transaction';
import type { charge } from './charge';
import type { payment_flows_payment_intent_presentment_details } from './payment_flows_payment_intent_presentment_details';
import type { payment_intent } from './payment_intent';
import type { refund_destination_details } from './refund_destination_details';
import type { refund_next_action } from './refund_next_action';
import type { transfer_reversal } from './transfer_reversal';
/**
 * Refund objects allow you to refund a previously created charge that isn't
 * refunded yet. Funds are refunded to the credit or debit card that's
 * initially charged.
 *
 * Related guide: [Refunds](https://stripe.com/docs/refunds)
 */
export type refund = {
    /**
     * Amount, in cents (or local equivalent).
     */
    amount: number;
    /**
     * Balance transaction that describes the impact on your account balance.
     */
    balance_transaction?: (string | balance_transaction) | null;
    /**
     * ID of the charge that's refunded.
     */
    charge?: (string | charge) | null;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created: number;
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
     */
    currency: string;
    /**
     * An arbitrary string attached to the object. You can use this for displaying to users (available on non-card refunds only).
     */
    description?: string;
    destination_details?: refund_destination_details;
    /**
     * After the refund fails, this balance transaction describes the adjustment made on your account balance that reverses the initial balance transaction.
     */
    failure_balance_transaction?: (string | balance_transaction);
    /**
     * Provides the reason for the refund failure. Possible values are: `lost_or_stolen_card`, `expired_or_canceled_card`, `charge_for_pending_refund_disputed`, `insufficient_funds`, `declined`, `merchant_request`, or `unknown`.
     */
    failure_reason?: string;
    /**
     * Unique identifier for the object.
     */
    id: string;
    /**
     * For payment methods without native refund support (for example, Konbini, PromptPay), provide an email address for the customer to receive refund instructions.
     */
    instructions_email?: string;
    /**
     * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: Record<string, string> | null;
    next_action?: refund_next_action;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object: refund.object;
    /**
     * ID of the PaymentIntent that's refunded.
     */
    payment_intent?: (string | payment_intent) | null;
    /**
     * Provides the reason for why the refund is pending. Possible values are: `processing`, `insufficient_funds`, or `charge_pending`.
     */
    pending_reason?: refund.pending_reason;
    presentment_details?: payment_flows_payment_intent_presentment_details;
    /**
     * Reason for the refund, which is either user-provided (`duplicate`, `fraudulent`, or `requested_by_customer`) or generated by Stripe internally (`expired_uncaptured_charge`).
     */
    reason?: refund.reason | null;
    /**
     * This is the transaction number that appears on email receipts sent for this refund.
     */
    receipt_number?: string | null;
    /**
     * The transfer reversal that's associated with the refund. Only present if the charge came from another Stripe account.
     */
    source_transfer_reversal?: (string | transfer_reversal) | null;
    /**
     * Status of the refund. This can be `pending`, `requires_action`, `succeeded`, `failed`, or `canceled`. Learn more about [failed refunds](https://stripe.com/docs/refunds#failed-refunds).
     */
    status?: string | null;
    /**
     * This refers to the transfer reversal object if the accompanying transfer reverses. This is only applicable if the charge was created using the destination parameter.
     */
    transfer_reversal?: (string | transfer_reversal) | null;
};
export namespace refund {
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    export enum object {
        REFUND = 'refund',
    }
    /**
     * Provides the reason for why the refund is pending. Possible values are: `processing`, `insufficient_funds`, or `charge_pending`.
     */
    export enum pending_reason {
        CHARGE_PENDING = 'charge_pending',
        INSUFFICIENT_FUNDS = 'insufficient_funds',
        PROCESSING = 'processing',
    }
    /**
     * Reason for the refund, which is either user-provided (`duplicate`, `fraudulent`, or `requested_by_customer`) or generated by Stripe internally (`expired_uncaptured_charge`).
     */
    export enum reason {
        DUPLICATE = 'duplicate',
        EXPIRED_UNCAPTURED_CHARGE = 'expired_uncaptured_charge',
        FRAUDULENT = 'fraudulent',
        REQUESTED_BY_CUSTOMER = 'requested_by_customer',
    }
}

