/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { payment_method } from './payment_method';
import type { payment_method_details_card_present_offline } from './payment_method_details_card_present_offline';
export type setup_attempt_payment_method_details_card_present = {
    /**
     * The ID of the Card PaymentMethod which was generated by this SetupAttempt.
     */
    generated_card?: (string | payment_method) | null;
    /**
     * Details about payments collected offline.
     */
    offline?: payment_method_details_card_present_offline | null;
};

