/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { mandate } from './mandate';
import type { payment_method } from './payment_method';
export type setup_attempt_payment_method_details_ideal = {
    /**
     * The customer's bank. Can be one of `abn_amro`, `asn_bank`, `bunq`, `buut`, `handelsbanken`, `ing`, `knab`, `moneyou`, `n26`, `nn`, `rabobank`, `regiobank`, `revolut`, `sns_bank`, `triodos_bank`, `van_lanschot`, or `yoursafe`.
     */
    bank?: setup_attempt_payment_method_details_ideal.bank | null;
    /**
     * The Bank Identifier Code of the customer's bank.
     */
    bic?: setup_attempt_payment_method_details_ideal.bic | null;
    /**
     * The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
     */
    generated_sepa_debit?: (string | payment_method) | null;
    /**
     * The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
     */
    generated_sepa_debit_mandate?: (string | mandate) | null;
    /**
     * Last four characters of the IBAN.
     */
    iban_last4?: string | null;
    /**
     * Owner's verified full name. Values are verified or provided by iDEAL directly
     * (if supported) at the time of authorization or settlement. They cannot be set or mutated.
     */
    verified_name?: string | null;
};
export namespace setup_attempt_payment_method_details_ideal {
    /**
     * The customer's bank. Can be one of `abn_amro`, `asn_bank`, `bunq`, `buut`, `handelsbanken`, `ing`, `knab`, `moneyou`, `n26`, `nn`, `rabobank`, `regiobank`, `revolut`, `sns_bank`, `triodos_bank`, `van_lanschot`, or `yoursafe`.
     */
    export enum bank {
        ABN_AMRO = 'abn_amro',
        ASN_BANK = 'asn_bank',
        BUNQ = 'bunq',
        BUUT = 'buut',
        HANDELSBANKEN = 'handelsbanken',
        ING = 'ing',
        KNAB = 'knab',
        MONEYOU = 'moneyou',
        N26 = 'n26',
        NN = 'nn',
        RABOBANK = 'rabobank',
        REGIOBANK = 'regiobank',
        REVOLUT = 'revolut',
        SNS_BANK = 'sns_bank',
        TRIODOS_BANK = 'triodos_bank',
        VAN_LANSCHOT = 'van_lanschot',
        YOURSAFE = 'yoursafe',
    }
    /**
     * The Bank Identifier Code of the customer's bank.
     */
    export enum bic {
        ABNANL2A = 'ABNANL2A',
        ASNBNL21 = 'ASNBNL21',
        BITSNL2A = 'BITSNL2A',
        BUNQNL2A = 'BUNQNL2A',
        BUUTNL2A = 'BUUTNL2A',
        FVLBNL22 = 'FVLBNL22',
        HANDNL2A = 'HANDNL2A',
        INGBNL2A = 'INGBNL2A',
        KNABNL2H = 'KNABNL2H',
        MOYONL21 = 'MOYONL21',
        NNBANL2G = 'NNBANL2G',
        NTSBDEB1 = 'NTSBDEB1',
        RABONL2U = 'RABONL2U',
        RBRBNL21 = 'RBRBNL21',
        REVOIE23 = 'REVOIE23',
        REVOLT21 = 'REVOLT21',
        SNSBNL2A = 'SNSBNL2A',
        TRIONL2U = 'TRIONL2U',
    }
}

