/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { connect_account_reference } from './connect_account_reference';
import type { deleted_tax_id } from './deleted_tax_id';
import type { tax_id } from './tax_id';
export type subscriptions_resource_subscription_invoice_settings = {
    /**
     * The account tax IDs associated with the subscription. Will be set on invoices generated by the subscription.
     */
    account_tax_ids?: Array<(string | tax_id | deleted_tax_id)> | null;
    issuer: connect_account_reference;
};

