/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { tax_product_registrations_resource_country_options_canada } from './tax_product_registrations_resource_country_options_canada';
import type { tax_product_registrations_resource_country_options_default } from './tax_product_registrations_resource_country_options_default';
import type { tax_product_registrations_resource_country_options_default_inbound_goods } from './tax_product_registrations_resource_country_options_default_inbound_goods';
import type { tax_product_registrations_resource_country_options_europe } from './tax_product_registrations_resource_country_options_europe';
import type { tax_product_registrations_resource_country_options_simplified } from './tax_product_registrations_resource_country_options_simplified';
import type { tax_product_registrations_resource_country_options_united_states } from './tax_product_registrations_resource_country_options_united_states';
export type tax_product_registrations_resource_country_options = {
    ae?: tax_product_registrations_resource_country_options_default_inbound_goods;
    al?: tax_product_registrations_resource_country_options_default;
    am?: tax_product_registrations_resource_country_options_simplified;
    ao?: tax_product_registrations_resource_country_options_default;
    at?: tax_product_registrations_resource_country_options_europe;
    au?: tax_product_registrations_resource_country_options_default_inbound_goods;
    aw?: tax_product_registrations_resource_country_options_default;
    az?: tax_product_registrations_resource_country_options_simplified;
    ba?: tax_product_registrations_resource_country_options_default;
    bb?: tax_product_registrations_resource_country_options_default;
    bd?: tax_product_registrations_resource_country_options_default;
    be?: tax_product_registrations_resource_country_options_europe;
    bf?: tax_product_registrations_resource_country_options_default;
    bg?: tax_product_registrations_resource_country_options_europe;
    bh?: tax_product_registrations_resource_country_options_default;
    bj?: tax_product_registrations_resource_country_options_simplified;
    bs?: tax_product_registrations_resource_country_options_default;
    by?: tax_product_registrations_resource_country_options_simplified;
    ca?: tax_product_registrations_resource_country_options_canada;
    cd?: tax_product_registrations_resource_country_options_default;
    ch?: tax_product_registrations_resource_country_options_default_inbound_goods;
    cl?: tax_product_registrations_resource_country_options_simplified;
    cm?: tax_product_registrations_resource_country_options_simplified;
    co?: tax_product_registrations_resource_country_options_simplified;
    cr?: tax_product_registrations_resource_country_options_simplified;
    cv?: tax_product_registrations_resource_country_options_simplified;
    cy?: tax_product_registrations_resource_country_options_europe;
    cz?: tax_product_registrations_resource_country_options_europe;
    de?: tax_product_registrations_resource_country_options_europe;
    dk?: tax_product_registrations_resource_country_options_europe;
    ec?: tax_product_registrations_resource_country_options_simplified;
    ee?: tax_product_registrations_resource_country_options_europe;
    eg?: tax_product_registrations_resource_country_options_simplified;
    es?: tax_product_registrations_resource_country_options_europe;
    et?: tax_product_registrations_resource_country_options_default;
    fi?: tax_product_registrations_resource_country_options_europe;
    fr?: tax_product_registrations_resource_country_options_europe;
    gb?: tax_product_registrations_resource_country_options_default_inbound_goods;
    ge?: tax_product_registrations_resource_country_options_simplified;
    gn?: tax_product_registrations_resource_country_options_default;
    gr?: tax_product_registrations_resource_country_options_europe;
    hr?: tax_product_registrations_resource_country_options_europe;
    hu?: tax_product_registrations_resource_country_options_europe;
    id?: tax_product_registrations_resource_country_options_simplified;
    ie?: tax_product_registrations_resource_country_options_europe;
    in?: tax_product_registrations_resource_country_options_simplified;
    is?: tax_product_registrations_resource_country_options_default;
    it?: tax_product_registrations_resource_country_options_europe;
    jp?: tax_product_registrations_resource_country_options_default_inbound_goods;
    ke?: tax_product_registrations_resource_country_options_simplified;
    kg?: tax_product_registrations_resource_country_options_simplified;
    kh?: tax_product_registrations_resource_country_options_simplified;
    kr?: tax_product_registrations_resource_country_options_simplified;
    kz?: tax_product_registrations_resource_country_options_simplified;
    la?: tax_product_registrations_resource_country_options_simplified;
    lt?: tax_product_registrations_resource_country_options_europe;
    lu?: tax_product_registrations_resource_country_options_europe;
    lv?: tax_product_registrations_resource_country_options_europe;
    ma?: tax_product_registrations_resource_country_options_simplified;
    md?: tax_product_registrations_resource_country_options_simplified;
    me?: tax_product_registrations_resource_country_options_default;
    mk?: tax_product_registrations_resource_country_options_default;
    mr?: tax_product_registrations_resource_country_options_default;
    mt?: tax_product_registrations_resource_country_options_europe;
    mx?: tax_product_registrations_resource_country_options_simplified;
    my?: tax_product_registrations_resource_country_options_simplified;
    ng?: tax_product_registrations_resource_country_options_simplified;
    nl?: tax_product_registrations_resource_country_options_europe;
    no?: tax_product_registrations_resource_country_options_default_inbound_goods;
    np?: tax_product_registrations_resource_country_options_simplified;
    nz?: tax_product_registrations_resource_country_options_default_inbound_goods;
    om?: tax_product_registrations_resource_country_options_default;
    pe?: tax_product_registrations_resource_country_options_simplified;
    ph?: tax_product_registrations_resource_country_options_simplified;
    pl?: tax_product_registrations_resource_country_options_europe;
    pt?: tax_product_registrations_resource_country_options_europe;
    ro?: tax_product_registrations_resource_country_options_europe;
    rs?: tax_product_registrations_resource_country_options_default;
    ru?: tax_product_registrations_resource_country_options_simplified;
    sa?: tax_product_registrations_resource_country_options_simplified;
    se?: tax_product_registrations_resource_country_options_europe;
    sg?: tax_product_registrations_resource_country_options_default_inbound_goods;
    si?: tax_product_registrations_resource_country_options_europe;
    sk?: tax_product_registrations_resource_country_options_europe;
    sn?: tax_product_registrations_resource_country_options_simplified;
    sr?: tax_product_registrations_resource_country_options_default;
    th?: tax_product_registrations_resource_country_options_simplified;
    tj?: tax_product_registrations_resource_country_options_simplified;
    tr?: tax_product_registrations_resource_country_options_simplified;
    tz?: tax_product_registrations_resource_country_options_simplified;
    ua?: tax_product_registrations_resource_country_options_simplified;
    ug?: tax_product_registrations_resource_country_options_simplified;
    us?: tax_product_registrations_resource_country_options_united_states;
    uy?: tax_product_registrations_resource_country_options_default;
    uz?: tax_product_registrations_resource_country_options_simplified;
    vn?: tax_product_registrations_resource_country_options_simplified;
    za?: tax_product_registrations_resource_country_options_default;
    zm?: tax_product_registrations_resource_country_options_simplified;
    zw?: tax_product_registrations_resource_country_options_default;
};

